### ISSUE TITLE
shane,jeje) 로그인 및 회원가입 관련 제안

### ISSUE THREAD

**Issue by chief7852** [psh40963/DDIT_Project1#20]
![캡처](https://user-images.githubusercontent.com/74906815/103046012-0389b980-45ca-11eb-8f56-3650749429fe.PNG)
관리자와 회원 구분요소 GRADE 컬럼 추가
이에
필요유무 판단 의견 및 
회원가입시 관리자와 관리자 구분 사항 의견요구

**Comment by ShanePark** [comment]
관리자는 회원가입을 따로 받지 않아도 될 것 같습니다.
관리자 계정은 1개만 있으면 된다고 생각합니다.
코드상에서 관리자 구분을 IF(USER_ID == "admin") 으로 구분이 가능 하므로 관리자 관리하는 컬럼은 굳이 없어도 될 듯 합니다.

회원이 계속 늘어나도 보통 U_GRADE 값은 대부분이 null 로 들어가기 때문에 필요성이 크지 않다고 판단됩니다
