### ISSUE TITLE
고객센터 게시판 수정사항

### ISSUE THREAD

**Issue by chief7852** [psh40963/DDIT_Project1#24]
고객센터 안에 있는 테이블은 총 3개입니다
관리자용 = 공지
회원 = 건의사항, 식당추가문의

머릿 말 개념으로 실행하기 위해 테이블을 개별설치가아니라 
한테이블에 받아 쿼리로 뽑아오는것이 좋다고 판단해 테이블을 하나로 받았습니다.
![고객센터 테이블](https://user-images.githubusercontent.com/74906815/103064646-e4098580-45f7-11eb-98bc-ab2491b4e356.PNG)
![고객센터테이블 내용](https://user-images.githubusercontent.com/74906815/103064648-e4a21c00-45f7-11eb-87f5-4b825dff39cc.PNG)
확인후 피드백 부탁드립니다.

**Comment by ShanePark** [comment]
CONTENT를 하나로  ADD_CONTENT, CONTENT2 이렇게 나누지 말고 CONTENT 하나로만 두고
새로운 'CATEGORY' 컬럼에서 '공지사항' , '건의사항' , '식당추가문의' 로 나누는게 좋지 않을까요?
지금 데이터 구조에서는 ADD_CONTENT와 CONTENT2 둘중에 하나의 데이터는 무조건 NULL 이 될 수 밖에 없어요.

위의 데이터베이스 구조에서는 공지사항을 불러올때
select * from board 
where ADD_CONTENT IS NULL
이런 쿼리를 해야하는데, 이럴 경우 누군가가 글을 작성할때 내용을 넣지 않으면 그게 공지사항으로 인식될 수 있습니다
