### ISSUE TITLE
issac ) restaurant DB 추가 1건 건의드립니다

### ISSUE THREAD

**Issue by ShanePark** [psh40963/DDIT_Project1#28]
![image](https://user-images.githubusercontent.com/74809918/103089114-5433fd80-4630-11eb-9f4b-0947d010a113.png)

우리 와이프가 꼭좀 넣어달라며 우리 프로그램 이용해서 손수 식당 추가 하셨습니다.. 
식당 DB 추가할때 얘도 꼭좀 추가해주십셔 담당자님 (__)🙏

**Comment by chief7852** [comment]
추가하였습니다ㅋㅋㅋㅋㅋㅋㅋㅋ
