### ISSUE TITLE
jeje, issac) USER_PICK 테이블 건의사항

### ISSUE THREAD

**Issue by ShanePark** [psh40963/DDIT_Project1#29]
RES_NAME
USER_ID

두개의 컬럼값이 있고, primary key 는 복합키로 하는데 문제가 없습니다.

다만,
찜리스트 구현을 하려는 중에 '찜 리스트에 나오는 식당들 목록을 어떤 규칙으로 나열한 것인가' 에서 고민이 생깁니다.
1. 찜한 날짜 최신순 (가장 시중에 나와있는 프로그램들이 많이 사용하는 것 같습니다) 
   - 1번으로 구현시에 USER_PICK  테이블 상에 DATE  컬럼이 추가되어야 합니다.
2.  식당의 평점 기준  
  -  2번으로 구현시에 쿼리가 조금 더 복잡해지긴 하지만 지금 테이블 구조로 문제 없이 구현이 가능합니다
  -  하지만 새로 찜한 식당의 평점이 낮거나 평점이 없을 경우에 찜 리스트에서 찾기가 굉장히 어려운 문제가 있습니다.
3. 식당의 이름 (가나다 순)
  -  이경우에도 테이블 조인이 필요하지만, 2번에 비해 간단합니다. ( 평점은 식당 테이블에 존재하지 않지만 식당 이름은 존재하기 때문에 ) 
  -  원하는 식당을 찾을 때에도 생각보다 어렵지 않게 찾을 수 있습니다
4.  평점/ 리뷰수/ 이름/ 거리 순으로 정렬을 모두 지원
![image](https://user-images.githubusercontent.com/74809918/103118428-268f9880-46b2-11eb-9438-839202adc391.png)

대략 이런 모양이 될건데, USERMAIN View를 구현했던 것 이상의 코드상의 노력과 시간 투자가 필요합니다.
쿼리 자체는 찜리스트 테이블을 기존 restaurant 테이블에 조인만 시키면 되기 때문에 그렇게 복잡하지는 않지만,
선택할 수 있는 버튼만 총 11개의 경우의 수가 생깁니다.

'뒤로가기'를 제외하면 10가지의 경우를 새로 구현해야 합니다.

각자 의견을 내주세요. 4번의 안으로 갈 경우 최대한 빨리 기능구현을 시작해야 할 것 같습니다.

두분 모두 각각 댓글 달아주시면 issue close 하겠습니다

**Comment by chief7852** [comment]
저의 의견은 3번입니다
첫번째 이유는
 저희가 하고 있는 프로그램의 모델이되고있는 
대표적인 프로그램인 
요기요, 배달의 민족, 배달통 어플
등과 같은 어플들에서는 가나다 순으로 정렬이되어있습니다.

두번째 이유
만약 유저들이 실제 사용할 경우를 생각하며 
만드는 프로그램이기 때문에 시선을 다르게 해야하는데
찜목록 자체는 많은 가게들이 들어가지 않고 또한
굳이 여러가지 제약을 걸지 않고 어떤 식당인지 파악하고
있는 경우 찜목록에 넣는 경우가 대부분이기에
평점 리뷰 거리등은 불필요한 사항이될것같습니다.

**Comment by jeje0130** [comment]
저도 3번이 좋을 것 같습니다!!
유저들이 사용하기에 가나다순으로 되어있으면 찜한 가게 찾기가 편리할 것 같습니다!

**Comment by ShanePark** [comment]
의견 감사합니다 issue를 닫습니다
