### ISSUE TITLE
jeje, issac) USERS table에 컬럼추가에 대한 안건

### ISSUE THREAD

**Issue by ShanePark** [psh40963/DDIT_Project1#30]
현재 USERS 테이블에는

USER_ID, NICKNAME, PASSWORD 

세개의 컬럼값이 있습니다.

우리의 프로그램 기능 상에서 더 이상의 컬럼은 불필요하기 때문인데요,

[도시락 주문] 기능이 핵심 기능중 하나로 추가되면서
개인들의 신상에 대한 특정화에 대한 필요성이 대두됩니다.

'실명', '핸드폰번호' 정도가 필수로 들어가야 할 듯 한데요
회원가입시에 받는게 일반적이지만 , 우리의 프로그램 특성상 (Console에서 작동)
처음부터 모든 입력을 받기엔 번거로운게 사실입니다.

건의드리는 내용은,
USERS 테이블에 NAME (VARCHAR2), PHONE (VARCHAR2, 정규화 필요)
두가지 테이블 (혹은 필요하다면 그 이상) 을 추가하되, NULLABLE 하게 구현을 해서
회원가입시 굳이 받지는 않지만, 
'도시락주문'등의 특별히 본인 확인이 필요한 메뉴에 대한 사용을 위해서는 
선택적으로 실명, 핸드폰번호 등을 입력 받게끔 하는게 좋지 않을까 싶습니다.

'도시락주문' 메뉴를 누르면 쿼리상에서 '실명'과 '핸드폰번호'가 정상적으로 기입된 회원인지를 체크하고
통과가 되면 도시락 주문 메뉴로, 통과가 안되면 '실명확인'(*가칭) 메뉴로 들어가서 이름과 핸드폰번호를 입력 받게끔
하는 기능을 생각하고 있습니다.

각자 해당 사항에 대해 의견을 주세요

**Comment by chief7852** [comment]
대부분 찬성 , 일부 다른의견

우선 이 안건이 나온것에대해 도시락주문에서 본인확인이 필요한 이유가
가장 중요한것 같습니다 예를들어 지금 현재 카카오톡으로 받고있는
주문여부에서 비용 미지불 확인과 같은 이유이면 실명이 필요할것 같습니다.
핸드폰번호의 경우 있어도 그만 없어도 그만인 경우일 수 있을것 같아 
세부적인 이유에관한 설명을 부탁드리겠습니다.

**Comment by ShanePark** [comment]
핸드폰번호는 있어도 그만 없어도 그만이 맞습니다. 굳이 추가하고자 하는 이유를 들자면
1. 실명만으로는 '동명이인'이 존재할시에 대응하기가 부족합니다. 우리반에는 동명이인이 없는 듯 하지만, 동명이인이 있다는걸 가정할때는 PrimaryKey에 준하는 다른 구분방법이 필요합니다. '생년월일'도 좋은 방안이 될테지만, 이름이 같고 생년월일도 같은 사람이 없으란 법은 없지요. 핸드폰 번호의 경우에는 그 누구도 겹치지 않는 Primary Key로 사용할 수 있을 정도의 개인화된 값입니다.
2. 지금의 회원가입 프로세스를 수정하지 않고 ( 회원가입시 입력할 것이 많아지면 콘솔 특성상 회원가입 피로도가 많이 심각해지면서 가입 단계가 루즈해 질 수 있음. 요즘 웹사이트들의 추세가 간단 : 가입버튼 - 이메일주소, 비밀번호 입력-> 가입완료 해지는 방향임을 감안), 회원 가입을 한 이후에 추후 추가 기능을 사용하려면 메인-내정보 관리에 들어가서 실명 등의 추가 정보를 입력 할 수 있게끔 할 생각입니다.  이왕 추가하는거 '실명' 외에 받을만한 값이 뭐가 있을까 하다가..
  [ 주소 ] : 너무 민감한 개인정보
  [ 생년월일 ] : 입력 받으면 좋겠다고 생각함- 생일을 챙겨줄 수 있음, 개인 구분에 제법 괜찮은 key
  [ 핸드폰번호 ] : 적당한 개인정보에 적당한 필요성.  관리자가 회원에게 직접 연락을 해야할 중요한 상황에 최고의 정보
  [ 이메일주소] : client가 이메일을 꾸준히 잘 확인하고, 회신도 한다는 가정하에는 핸드폰 번호와 동급 정보. 이메일 확인을 전혀 하지 않을 경우에는 소통의 방법으로는 전혀 사용할 수 없음.


이렇게 쓰다보니, 프로그램 내에서 [친구추가], [메시지보내기] , [메시지확인] 등의 기능이 추가되면 프로그램의 기능상 볼륨이 크게 확장 될 수 있을 것 같다는 생각도 듭니다. 

도시락 주문시  ' 적립금' 의 형태로, 각자 개인의 계정에 사이버머니 [: 관리자에게 입금하여 충전받거나 결재 시스템을 탑재]  를 충전해서 매일매일 주문자에게 따로 입금을 할 번거로움 없이 적당한 금액( 만원씩) 충전 후 사이버머니를 차감하는 식으로 주문 과정을 자동화 하는것도 좋을 것 같습니다.  [ 이경우 user 테이블에 잔액을 저장할 컬럼이 추가되어야함 ]

**Comment by chief7852** [comment]
정리 해주셔서 감사합니다.
중복확인을 코드화 시켜 체크한다면 괜찮을것 같아
핸드폰 번호의 경우 일단 추가를 해놓았습니다.
다른 추가사항에서
친구 추가의 경우에는 사용 용도가 많을것 같아 긍정적으로보입니다
예를들어 친구가 찜한 식당을 볼수있는 등 구현에좋을것같습니다
메시지 같은경우는 약간은 저희가 만드는 프로그램에서 투머치요소인느낌이 
쬐끔듬니다..
적립금같은경우는 저도 생각을 해보았었습니다.
저의 경우에는 가게에 연동할 요소가 부족하다 생각하여
의견을 제시하지 않았었는데 굉장히 좋은것 같습니다.
관리자가 계속해서 본다는 가정하에
관리자 기능에 도시락 주문을 확인하여 그 수에 맞게 주문시킨다면
충분히 구현가능할것 같습니다.

**Comment by ShanePark** [comment]
서버상에서 사용자의 충전 기능 사용시 관리자의 핸드폰에 push 알림이 오게끔 한다면,
관리자가 핸드폰을 통해서 입금도 확인할테니, 입금여부에 대한 확인 후 충전 승인도 가능 할 듯 합니다.

도시락 주문확인의 경우에는 지금 도시락 모아서 주문하시는 분이 하는것처럼
정해진 시간( 예 : 오후 11시 50분) 에 자동으로
도시락주문해주는 분에게 핸드폰으로 "ㅇㅇ월 ㅇㅇ일 도시락 주문 총 ㅇㅇ명 주문자 : 홍길동, 김땡떙, 이아무개, ..."
라고 text 나 핸드폰 카카오톡 push 알림을 보내주는 기능을 만들어 추가한다면
아주 잘 하면 우리 발표때까지 302호 공식 프로그램을 런칭하는것도 가능하지 않을까 싶습니다.

도시락 주문하시는분에게 프로그램상 상당수의 권한( 적립금 충전 승인, 주문자 핸드폰번호 보기 등)을 
 '아이디' or '닉네임' 구분을 통해 주는것도 프로그램 상에서 가능할듯합니다.

**Comment by chief7852** [comment]
이것이 가능한검가유

**Comment by ShanePark** [comment]
서버에서 이메일 보내주는 것 까진 어제 성공했는데 문자나 푸쉬알림까지 가려면 어나더레벨이긴 합니당
