### ISSUE TITLE
jeje) 마이페이지 관련

### ISSUE THREAD

**Issue by ShanePark** [psh40963/DDIT_Project1#31]
![image](https://user-images.githubusercontent.com/74809918/103121867-6f028280-46c1-11eb-97a2-8d4fb4ae3b80.png)
[기존] ↑

수정 ↓

1.  □■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■
2. 
3.                                    🍽️ 오늘 뭐먹지? 🍽️
4. 
5.                                   🧑마이페이지👩
6.                                     ■ 찜리스트
7.                                     □ 주문내역
8.                                     □ 내 리뷰 확인
9.                                     □ 계정관리
10.                                   □ 뒤로가기                               (2)↓ (5)↑ (⏎)확인 
11.  □■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■
12.  >

* 콘솔창에서 맨 아래줄은 '입력'을 받기 위한 한줄을 빼야합니다. 
  총 12줄로 잡는다고 생각하면, 1번과 11번줄을 ■□■□■□■□■ 로 해주세요

* 대부분의  콘솔화면에서는 '뒤로가기'버튼이 있어야 합니다. 그렇지 않으면 뒤로 가기 위해서 무조건
프로그램을 새로 켰다 켜야 하는 불상사가 발생하게 됩니다.
지금 (2),(5) 숫자입력을 아래,위 이동키로 받고 있는것처럼  (1) 번을 입력시 뒤로 가기 기능을 고민중에 있습니다.
확정되기 전까지는 뒤로가기 버튼을 포함해주세요

* 탈퇴'와 '로그아웃' 을 계정관리로 묶는게 좋을 듯 합니다.  화면에 여유가 생기면 로그아웃을 다시 앞으로 빼오는 것도 괜찮을 것 같습니다.  계정삭제, 로그아웃 뿐 아니라 '회원정보수정' 이 필요합니다.
여유가 된다면 '계정관리' 콘솔뷰도 만들어주세요

**Comment by jeje0130** [comment]
네 알겠습니다~!

**Comment by ShanePark** [comment]
계정 관리 엄청 디테일하게 만들어 주셨네요 감사합니다
