### ISSUE TITLE
issac) USER_PICK 테이블 수정이 필요합니다

### ISSUE THREAD

**Issue by ShanePark** [psh40963/DDIT_Project1#32]
![image](https://user-images.githubusercontent.com/74809918/103127417-13da8b00-46d5-11eb-808f-083dd794263d.png)
현재 다음과 같이 되어있습니다.
res_name은 중복이 가능하므로, restaurants 의 PK 인 res_id 로 조인해야 합니다.

![image](https://user-images.githubusercontent.com/74809918/103127456-353b7700-46d5-11eb-9949-e4fef6f94f05.png)

위와 같이 수정하면 될 듯 합니다.

**Comment by chief7852** [comment]
확인하였습니다 수정 후 올리겠습니다

**Comment by chief7852** [comment]
수정완료

**Comment by ShanePark** [comment]
감사합니다
