### ISSUE TITLE
SHANE) USER TABLE 추가중 문제점

### ISSUE THREAD

**Issue by chief7852** [psh40963/DDIT_Project1#34]
USER테이블에 NAME과 PHONE  컬럼 추가후 테스트 과정에서
PHONE넘버 중복체크 결함이 생김
PHONE을 PK 설정시 문제점 = NOTNULL   = 회원가입 불가
PHONE을 PK 설정 하지 않을시 = 중복값 생성가능

가능한 방법
JAVA 에서 데이터를 불러와 중복체크 후 생성가능하게 만들어야함

다른 방법이나 잘못된 부분 지적 부탁드립니다.

**Comment by ShanePark** [comment]
현재 우리가 사용하고 있는 '닉네임' 과 비슷한 상황이네요.
주말동안 닉네임 중복을 확인하는 코드를 추가 해서 문제 없이 잘 작동하고 있는 상태입니다.
DB 상에서는 NULLABLE 로 체크해서, 가입시에 전화번호 없이 가입하고, 
추후 전화번호 입력 시에 전화 번호 중복 체크를 하면 해결할 수 있을 듯 합니다.


https://user-images.githubusercontent.com/74809918/103143660-3369c600-475e-11eb-9af0-336b0032b3f2.mp4

**Comment by chief7852** [comment]
저렇게 구현가능하다면 좋은것같습니다

**Comment by ShanePark** [comment]
지적 날카로웠어요 👏👏👏
