### ISSUE TITLE
jeje, issac) 식당에 전화번호 데이터 관련

### ISSUE THREAD

**Issue by ShanePark** [psh40963/DDIT_Project1#36]
![image](https://user-images.githubusercontent.com/74809918/103143979-c443a000-4764-11eb-8d66-686c083e867b.png)

![image](https://user-images.githubusercontent.com/74809918/103143980-cf96cb80-4764-11eb-8767-888a0dec7bc0.png)

메뉴상에는 전화번호가 있고, DB 상에는 전화번호가 없습니다.
전화번호를 추가할지 없앨지 의견을 합쳐주세요~
굳이 없어도 될거 같기도 하고.. 있음 좋을 거 같기도 하고 애매하긴 하네요

일단 전화번호 없이 기능구현 해놓을게요 추후에 의견 종합한후 추가하겠습니다.

**Comment by chief7852** [comment]
전화번호...실수했습니다 넣고 다시 올리겠습니다.
