### ISSUE TITLE
jeje,shane) 딜레이 관련 인터페이스 건의

### ISSUE THREAD

**Issue by chief7852** [psh40963/DDIT_Project1#38]
로그인이나 게시판같은 기능 구현시 길지는 않지만 데이터를 불러오는 딜레이가 있습니다
중요한것은 아니지만 할수있는부분의 디테일적인 부분을 넣고싶은 
작은 소원이있습니당 0.5초 딜레이부분의 지루함을 위해 로딩인터페이스를 추가하고싶습니다!

**Comment by ShanePark** [comment]
인터페이스의 연속성을 저해하지 않는 선에서 좋은 추가점이 될 것 같습니다.

처음 프로그램을 시작했을때도 

![image](https://user-images.githubusercontent.com/74809918/103149141-296db480-47aa-11eb-848c-249e0f7d2fce.png)

이 화면이 한번에 나오는게 아니라 딜레이를 이용해서 깔끔하고 임팩트있는 이펙트와 함께 시작이 되면 좋겠네요

해당 프로그램의 전체적인 그래픽 디자인을 @jeje0130 가 만들어줬으니,

  jeje에게 월요일에 로딩인터페이스에 대해 아이디어를 얻도록 하죠

**Comment by chief7852** [comment]
예 저는 형의 코드리딩에 죽을맛입니다...

**Comment by ShanePark** [comment]
보이기만 복잡해 보여도 차근차근 코드 읽어보면 다 우리가 써봤던 기능들이라이해 할 수 있습니다 !
틈날때마다 코드 보기좋게 정돈하고 주석도 최대한 달겠습니다
