### ISSUE TITLE
발표일까지 대략적인 일정

### ISSUE THREAD

**Issue by ShanePark** [psh40963/DDIT_Project1#42]
* 월요일
@chief7852 게시판 만들기 숙달 후 '고객센터'쪽 만들기
@psh40963  리뷰관련 모든 기능 + 식당의 메뉴 관련 모든 기능 추가
@jeje0130  필요한 콘솔 화면들이 꽤 많습니다. 고객센터 관련해서 @chief7852 와 적절한 피드백을 주고 받아서 적절한 틀을 만들어주세요.  사용자가 식당 추가나 메뉴 추가에대한 신청을 하면 관리자가 [승인] 혹은 [거절] 이 가능하다면 더욱 좋을 것 같습니다.

*화요일
@jeje0130  '음식스타일'로 검색 기능 추가하기 , '메뉴로 검색' 기능 추가하기
  :  메인-검색 에서 '이름별로검색' '음식스타일로검색' '메뉴로검색'  세가지로 세분화 할 예정입니다.
@psh40963 도시락 관련 모든 기능 추가
@chief7852 계정관리 기능 추가 ( 닉네임변경, 회원탈퇴 : 탈퇴시 기존에 있던 ID는 새로 가입이 안되도록 적용 )
- 기존에 달았던 리뷰 등의 문제로 아이디,닉네임은 탈퇴하더라도 다시 사용하지 못하게 하는 편이 좋을 듯 합니다.

* 수요일 오전
@jeje0130 PPT 는 수요일 점심때까지 최대한 완성시켜주세요.
각각의 임무가 들어간다면 저희 셋 자리순으로 프론트엔드/ 데이터베이스 / 백엔드 가 적당할 듯 합니다.
  * PPT 내용중 '우리가 사용한 기술들'에 대한 내용이 추가되면 좋을 것 같습니다.
https://youtu.be/j--QClQQ0Vs?t=202

동영상 3분 22초에 나오는게 기술 설명입니다. 우리는 Github, sourcetree, Oracle, SQL Developer, JDBC, eclipse, ASW 정도 사용된 것 같습니다. 중간중간 깃헙에서 우리가 issue로 나눴던 부분중 괜찮은 부분들을 떼내서 발표자료에 사용하는 것도 좋을 듯 합니다. Github 이나 sourcetree 가 협업에 적극적으로 쓰였고 많은 도움이 된 만큼 발표에서 소개되면 반응도 좋지 않을까 싶습니다

@psh40963 프로그램도 수요일 점심때까지 마무리 짓도록 할게요.
@chief7852 프로그램 기능추가를 함께 하거나 DB쪽을 손봐주세요

*수요일 오후중
@jeje0130 완성된 프로그램을 이용해 발표에 대한 대략적인 PPT 흐름과 프로그램 흐름을 구상해주세요!
프로그램 흐름에 대해 대략적이라도 구상이 되면 간단하게 정리해서 보내주세요, 어느정도 흐름을 암기하겠습니다.
@chief7852 저와 프로그램 테스팅(버그 찾기) 및 DB 추가를 함께 해주세요
* 수요일 저녁 식사 후
셋이서 4층 컨퍼런스룸에 모여서 같이 회의를 하고 발표 리허설을 해볼게요. ( 피드백 및 시연자와 합을 맞추기 위해서)

함께 3일만 더 고생해서 멋진 발표 준비해봅시다 화이팅!
언제든 자유롭게 의견 말씀해주세요

**Comment by chief7852** [comment]
확인했습니다 고생하셨습니다.
