### ISSUE TITLE
12월 28일 월요일 마감 전 마지막 issue

### ISSUE THREAD

**Issue by ShanePark** [psh40963/DDIT_Project1#45]
1. 식당 세부화면에서 '메뉴'보기 및 관리자의 메뉴 추가 기능을 추가했습니다.
 페이징처리를 새로운 방법으로 해보았는데 병합-> 테스트 이후 피드백 주세요. 

2. 식당관리쪽에 메뉴를 넣는 기능을 추가했습니다. 아무래도 관리자 메뉴이다 보니 메뉴 줄맞춤에 시간을 투자하지 않고 간단한 인터페이스에서 저희가 메뉴 등록을 간편하게 할 수 있는 방향으로 구현했습니다. 메뉴추가시 aws 서버로 JDBC 연결을 돌려서 등록하면 전보다 간단하게 메뉴를 업데이트 할 수 있을 듯 합니다.

내일 (화) 하루는 우리의 핵심 기능인 [도시락 주문 관련 기능] 에 총력을 기울일 예정입니다.

앞으로 추가될 기능으로
[도시락 관련 기능]
[계정관련] - 닉네임 변경, 회원 탈퇴,  전화번호,실명 등록
[몇가지 추가 검색기능] - 메뉴로검색, 음식스타일로 검색 - jeje
[고객센터] -  건의사항 및 식당,메뉴 추가 건의 - issac
[로딩관련] - jeje 와 issac이 디자인& 구현을 생각해주세요. 혹 구현이 덜된다면 도시락 기능 추가 후 돕겠습니다

정도 입니다. 당장의 프로그램 구동에 치명적으로 필요한 기능은 거의 남아있지 않다고 생각되지만, 꼭 구현되어야 하는데 놓치고 있다는 기능을 프로그램 구동 중 발견했거나 생각난다면 말씀해주세요.

**Comment by chief7852** [comment]
고객센터 내일 오전중으로 마무리하겠습니다.
