### ISSUE TITLE
별점 주는 방식 및 디자인 건의드립니다.

### ISSUE THREAD

**Issue by jeje0130** [psh40963/DDIT_Project1#47]
□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■

                                🍽️ 오늘 뭐먹지? 🍽️

	[괴산올갱이]

주고싶은 별점을 선택해주세요
■ 뒤로가기 □ ★☆☆☆☆□ ★★☆☆☆□ ★★★☆☆□ ★★★★☆□ ★★★★★
□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■

기존에 별점주는 방식이 저렇게 선택하는 방식이였는데 
혹시 저희 예전에 수업시간에 에어컨 풍량 조절했던 식으로 
별을 추가 값을 입력받아서 별을 채운 후 그 값을 콘솔에 보여지는 방식은 어떠신가요~???

ex)
void showCapacity(){
		System.out.print("평점. ");
		for(int i = MIN_CAP + 1; i <= MAX_CAP; i++){
			if(i <= capacity){
				System.out.print("★");
			}else{
				System.out.print("☆");
			}
		}
		System.out.println();
		
	}
	void showCapacity2(){
		System.out.print("평점. ");
		for(int i = MIN_CAP + 1; i <= MAX_CAP; i++){
			if(i <= capacity){
				System.out.print("★");
			}else{
				System.out.print("☆");
			}
		}
		System.out.println();
	}

□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■

                                          🍽️ 오늘 뭐먹지? 🍽️

	                        [괴산올갱이]    ★★★☆☆

                                  주고싶은 평점을 입력해주세요
                 □ 뒤로가기  ■ 별 추가  □ 별 삭제   □ (⏎)확인
□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■□■
입력> 5                 평점. ★★★☆☆

**Comment by ShanePark** [comment]
좋은듯 합니다! 적극 반영해서 도시락 기능 추가후에 적용시키겠습니다

**Comment by ShanePark** [comment]
업데이트 완료 했습니다 이슈를 닫습니다
