### ISSUE TITLE
jeje ) 쿼리 수정 필요합니다.

### ISSUE THREAD

**Issue by ShanePark** [psh40963/DDIT_Project1#52]
@jeje0130 

오늘 식당 목록을 불러온 쿼리에서 

점수와 찜 갯수를 쿼리에서 불러 오지 않았습니다.

점수와 찜이 식당에 존재하는지 여부를 떠나서, 애초에 불러온 값이 없으니 모든 식당이 평점0 추천수 0 으로 됩니다.

서브쿼리를 넣어서 만들어야합니다.

제가 UserDao Method 들입니다. 각각 거리순/ 점수순/ 리뷰갯수순/ 이름으로 검색 입니다.

위 쿼리를 참고 해서 요리스타일로 식당 조회하는 쿼리를 다시 짜주세요! 

(예상 소요 시간 : 1분 ~ 10분 )

	
	public List<Map<String,Object>> resByDistance(){
		String sql =  "select a.*, nvl(score,0) score, nvl(rv_cnt,0) rv_cnt, nvl(c.cnt,0) pick_cnt"
				       +" from restaurants a, "
						   +" (select res_id , round(avg(grade),1) score, count(*) rv_cnt"
							  +" from review"
							 +" group by res_id) b,"
						   +" (select res_id, count(*) cnt"
							  +" from user_pick"
						     +" group by res_id) c"
					  +" where a.res_id = b.res_id(+)"
					   + " and a.res_id= c.res_id(+)"
				     +" order by distance";
		List<Map<String,Object>> list = jdbc.selectList(sql);
		
		return list;
	}
	
	public List<Map<String,Object>> resByScore(){
		String sql =  "select a.*, nvl(score,0) score, nvl(rv_cnt,0) rv_cnt, nvl(c.cnt,0) pick_cnt"
			          +" from restaurants a, "
					   +" (select res_id , round(avg(grade),1) score, count(*) rv_cnt"
						  +" from review"
						 +" group by res_id) b,"
					   +" (select res_id, count(*) cnt"
						  +" from user_pick"
					     +" group by res_id) c"
				  +" where a.res_id = b.res_id(+)"
				   + " and a.res_id= c.res_id(+)"
				  +" order by score desc";
				     
		List<Map<String,Object>> list = jdbc.selectList(sql);
		
		return list;
	}
	
	public List<Map<String,Object>> resByRvcnt(){
		String sql =  "select a.*, nvl(score,0) score, nvl(rv_cnt,0) rv_cnt, nvl(c.cnt,0) pick_cnt"
		          +" from restaurants a, "
				   +" (select res_id , round(avg(grade),1) score, count(*) rv_cnt"
					  +" from review"
					 +" group by res_id) b,"
				   +" (select res_id, count(*) cnt"
					  +" from user_pick"
				     +" group by res_id) c"
			  +" where a.res_id = b.res_id(+)"
			   + " and a.res_id= c.res_id(+)"
			  +" order by rv_cnt desc";
		List<Map<String,Object>> list = jdbc.selectList(sql);
		
		return list;
	}
	
	public List<Map<String,Object>> resByName(String name){
		String sql =  "select a.*, nvl(score,0) score, nvl(rv_cnt,0) rv_cnt, nvl(c.cnt,0) pick_cnt"
		          +" from restaurants a, "
				   +" (select res_id , round(avg(grade),1) score, count(*) rv_cnt"
					  +" from review"
					 +" group by res_id) b,"
				   +" (select res_id, count(*) cnt"
					  +" from user_pick"
				     +" group by res_id) c"
			  +" where a.res_id = b.res_id(+)"
			   + " and a.res_id= c.res_id(+)"
			    +" and res_name like ?"
			  +" order by rv_cnt desc";
		List<Object> p = new ArrayList<>();
		p.add("%"+name+"%");	// %를 쿼리에 String sql 에 쓰면 에러가 납니다. 아에 파라미터로 보내야 합니다.
		List<Map<String,Object>> list = jdbc.selectList(sql,p);
		
		return list;
	}

**Comment by ShanePark** [comment]
SQL developer에서 쿼리 수정 해서 조회 잘 되는지 여부 확인 한 후에 이슈 클로즈 해주세요!

**Comment by jeje0130** [comment]
조회 잘 됩니다!!! 마지막에 정렬을 평점이 높은 순부터 나오도록 정렬해봤습니다!!

![image](https://user-images.githubusercontent.com/76428816/103324244-084ae380-4a8a-11eb-8731-6b82a80ad9f4.png)

**Comment by ShanePark** [comment]
평점 순으로 정렬하는거 아주 좋아요~~

![image](https://user-images.githubusercontent.com/74809918/103324684-ec484180-4a8b-11eb-9d88-f1f9fe08a25f.png)

Dao에 그대로 적용하였습니다!
