### ISSUE TITLE
issac ) 게시판 확인 요청

### ISSUE THREAD

**Issue by ShanePark** [psh40963/DDIT_Project1#53]
@chief7852 

게시판 페이징 확인 한번 해주세요
321 654 87 이런식으로 페이징이 되어있어요
어렵지 않게 해결 할 수 있을겁니다 화이팅!

**Comment by ShanePark** [comment]
코드는 진짜 기가막히게 잘붙었습니다 소름돋네요

**Comment by chief7852** [comment]
123 456 789 로 변경말씀하시는건가요??
일부로 역순으로 쿼리작성한건데 수정하겠습니다

**Comment by ShanePark** [comment]
987 654 321 순으로 나오는게 맞지 않나요?

**Comment by ShanePark** [comment]
수정사항 확인했습니다 완벽합니다
