### ISSUE TITLE
2020년 12월 30일 (수요일) 세부 일정

### ISSUE THREAD

**Issue by ShanePark** [psh40963/DDIT_Project1#54]
[ 남아있는 추가가 필요한 기능 목록 ]
(계정관련 ) 닉네임 변경, 회원 탈퇴, 도시락 주문 내역 보기
(검색관련 ) 메뉴로검색, 음식스타일로 검색 - 음식스타일 검색은 거의 완료. 메뉴로 검색도 금방 가능할 듯 해 보임.
(로딩관련 ) console 에있던 화면들을 로딩용으로 다듬어내기 . wait 메서드 활용하기
(식당관리) 메뉴삭제

[ 오전일정 ]
@psh40963  : 남아있는 추가 기능들 구현하기
@chief7852  :  고객센터쪽 마무리 짓기, 시간이 남으면 프로그램 테스팅 & 피드백 (+ 로딩 화면 )
@jeje0130  : 음식스타일로 검색 마무리 짓기. PPT 제작 및 발표 준비
           - 발표 준비하면서 프로그램 기능들을 최대한 이것 저것 테스트 해 주세요. 본인이 직접 회원가입도 하나 해서 리뷰도 달아보고 찜도 해보고 도시락도 주문 해 보면서 기능상 문제가 있지는 않은지, 개선이 필요한 곳이 있는지 찾아주세요.
           
[오후일정 ]
@psh40963  : 버그 고치기, 개선사항 즉각즉각 반영해서 코드 다듬기, 식당 DB 추가하기
@chief7852  : 프로그램 최대한 테스팅 하며 버그 찾거나 개선사항 피드백 해주기. 식당 DB 추가하기 
@jeje0130  : 발표 프레젠테이션 구상하기. 프로그램 시연 흐름도 구상하기. 테스트용 아이디 10번정도 만들어보며 가봤던 식당들에 직접 리뷰달고 찜하기 ( 식당 DB 추가는 관리자 모드로 로그인 해서 직접 할 수 도 있고,  issac 에게 요청해도 됩니다. 아무래도 관리자 모드에서의 기능들도 한번씩 구동을 해보고 발표시에 포함될만한 항목이 있는지도 체크해주세요)

[저녁일정]
오후 6시 30분 ~ 9시 까지 총 2시간 30분중에 2시간정도를 프로젝트에 할애 할 수 있다고 가정하겠습니다.
오후 6시 30분 ~ 7시 컨퍼런스룸에서 자유롭게 의견을 나누며 처음으로 우리 팀의 대화의 시간을 가져보도록 하겠습니다
오후 7시 ~ 7시 30분 프로젝트 시연, 발표 리허설 및 피드백 나누기
7시 30분 ~   자유롭게 쉬엄쉬엄 마무리 하거나 아래 사항 중 필요한 사항 시행
1. 프로그램 개선사항이 남아있으면 반영하기
2. 프로젝트 코드에 쓰인 패턴 중 팀원이 잘 이해하지 못한 부분이 있으면 셋이서 논의 & 함께 설명하며 공부
3. 인터페이스 개선 및 DB 추가

발표 전 마지막 날입니다. 셋이서 정말 멋진 팀웍으로 쉬지않고 열심히 준비해온 만큼 우리의 프로젝트를 통해 올 한해 까지 마무리 잘 해냅시다! 이 프로젝트가 우리 셋의 성장과 앞날에 정말 큰 도움이 될 거라고 확신합니다.

**Comment by chief7852** [comment]
정리하시느라 고생하셨습니다
내일 마지막 마무리 깔끔하게 하고 발표 이후에도 각자 맡았던 부분 ,이해했고 어려웠던 부분들을 정리해서 이야기 나누면서 공유했으면 좋겠습니다!

**Comment by jeje0130** [comment]
고생하셨습니다! 마지막까지 모두 힘내세요👍👍
