### ISSUE TITLE
시연순서 확인해주세요

### ISSUE THREAD

**Issue by jeje0130** [psh40963/DDIT_Project1#77]
<시연순서>

1. 회원가입
2. 홈화면 소개 (아래로 내리며 - 베스트 5 소개)

3. 거리 기준으로 조회
- 맥도날드 조회 
- 맥도날드 : 메뉴보기, 리뷰보기 (메뉴 아래로 내려서 다음페이지도 보여주세요)
- 맥도날드 : 찜하기 (좋아하는 사람 수 늘어난 것 확인)

4. 검색기능 소개
- 메뉴명으로 검색
- 검색할 메뉴 입력
- 메뉴를 갖고있는 식당 중 한 곳 조회
- 해당 가게 메뉴 확인(짜장 메뉴가 있는지)

5. 마이페이지 소개
- 찜리스트 확인

6. 고객센터 소개
- 일반 건의사항 게시글 작성 및 조회 가능 설명
- 식당 문의 선택
- 원하는 식당 입력 (관리자의 승인 후 등록가능하다고 설명)

7. 도시락 주문 페이지 소개
- 개인정보 등록 후 다시 도시락 주문페이지
- 대전도시락 선택
- 주문하기 선택
- 적립금 충전 선택
- DB 적립금 충전
- 다시 주문하기 선택
- 주문 취소 화면 소개 

8. 홈화면 이동 후 종료

> 이렇게 진행해도 괜찮을까요??

**Comment by ShanePark** [comment]
감사합니다 확인해볼게요

**Comment by ShanePark** [comment]
PPT 19 페이지 소름 돋을정도네요 최고에요
